// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [
      TSubRelationship in Extract<
        TRelationship["fields"][number],
        prismic.CustomTypeModelFetchContentRelationshipLevel1
      > as TSubRelationship["id"]
    ]: ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
  } & // Group
  {
    [
      TGroup in Extract<
        TRelationship["fields"][number],
        | prismic.CustomTypeModelFetchGroupLevel1
        | prismic.CustomTypeModelFetchGroupLevel2
      > as TGroup["id"]
    ]: TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [
      TFieldKey in Extract<TRelationship["fields"][number], string>
    ]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [
    ID in Exclude<TCustomType[number], string>["id"]
  ]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type PartnerPageDocumentDataSlicesSlice =
  | HeroSlice
  | PartnerProgramSlice
  | ContactFormSlice
  | EdiExpertiseSlice
  | FooterSlice;

/**
 * Content for Partner Landing Page documents
 */
interface PartnerPageDocumentData {
  /**
   * Slice Zone field in *Partner Landing Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PartnerPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Partner Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: partner_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Partner Landing Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: partner_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Partner Landing Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Partner Landing Page document from Prismic
 *
 * - **API ID**: `partner_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PartnerPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PartnerPageDocumentData>,
    "partner_page",
    Lang
  >;

export type AllDocumentTypes = PartnerPageDocument;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
  /**
   * Headline field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * CTA_Label field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Copy field in *ContactForm → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_form.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactFormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault;

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: ContactForm
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<
  "contact_form",
  ContactFormSliceVariation
>;

/**
 * Item in *EdiExpertise → Default → Primary → Cards*
 */
export interface EdiExpertiseSliceDefaultPrimaryCardsItem {
  /**
   * Headline field in *EdiExpertise → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Copy field in *EdiExpertise → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.cards[].copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * Image field in *EdiExpertise → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *EdiExpertise → Default → Primary*
 */
export interface EdiExpertiseSliceDefaultPrimary {
  /**
   * Headline field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Copy field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * Quote field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.quote
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  quote: prismic.KeyTextField;

  /**
   * Cards field in *EdiExpertise → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: edi_expertise.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<Simplify<EdiExpertiseSliceDefaultPrimaryCardsItem>>;
}

/**
 * Default variation for EdiExpertise Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EdiExpertiseSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EdiExpertiseSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EdiExpertise*
 */
type EdiExpertiseSliceVariation = EdiExpertiseSliceDefault;

/**
 * EdiExpertise Shared Slice
 *
 * - **API ID**: `edi_expertise`
 * - **Description**: EdiExpertise
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EdiExpertiseSlice = prismic.SharedSlice<
  "edi_expertise",
  EdiExpertiseSliceVariation
>;

/**
 * Item in *Footer → Default → Primary → Links*
 */
export interface FooterSliceDefaultPrimaryLinksItem {
  /**
   * Label field in *Footer → Default → Primary → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Url field in *Footer → Default → Primary → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Footer → Default → Primary → Social_Links*
 */
export interface FooterSliceDefaultPrimarySocialLinksItem {
  /**
   * Platform field in *Footer → Default → Primary → Social_Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_links[].platform
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * Url field in *Footer → Default → Primary → Social_Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Logo field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Address field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.address
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  address: prismic.RichTextField;

  /**
   * Contact_general_label field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_general_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_general_label: prismic.KeyTextField;

  /**
   * Contact_general_phone field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_general_phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_general_phone: prismic.KeyTextField;

  /**
   * Contact_sales_label field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_sales_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_sales_label: prismic.KeyTextField;

  /**
   * Contact_sales_phone field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_sales_phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_sales_phone: prismic.KeyTextField;

  /**
   * Contact_na_label field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_na_label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_na_label: prismic.KeyTextField;

  /**
   * Contact_na_phone field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.contact_na_phone
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_na_phone: prismic.KeyTextField;

  /**
   * Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<FooterSliceDefaultPrimaryLinksItem>>;

  /**
   * Social_Links field in *Footer → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.social_links[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<FooterSliceDefaultPrimarySocialLinksItem>
  >;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Topline field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.topline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topline: prismic.KeyTextField;

  /**
   * Title field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Copy field in *Hero → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * CTA Primary field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_primary
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_primary: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Secondary field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.cta_secondary
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_secondary: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * UI Requests field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ui_requests
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ui_requests: prismic.ImageField<never>;

  /**
   * UI Inventory field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.ui_inventory
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  ui_inventory: prismic.ImageField<never>;

  /**
   * Video Thumbnail field in *Hero → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.video_thumbnail
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  video_thumbnail: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Item in *PartnerProgram → Default → Primary → Cards*
 */
export interface PartnerProgramSliceDefaultPrimaryCardsItem {
  /**
   * Headline field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Image field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Copy field in *PartnerProgram → Default → Primary → Cards*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[].copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;
}

/**
 * Primary content in *PartnerProgram → Default → Primary*
 */
export interface PartnerProgramSliceDefaultPrimary {
  /**
   * Topline field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.topline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  topline: prismic.KeyTextField;

  /**
   * Headline field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.headline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  headline: prismic.KeyTextField;

  /**
   * Copy field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.copy
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  copy: prismic.RichTextField;

  /**
   * Cards field in *PartnerProgram → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partner_program.default.primary.cards[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  cards: prismic.GroupField<
    Simplify<PartnerProgramSliceDefaultPrimaryCardsItem>
  >;
}

/**
 * Default variation for PartnerProgram Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerProgramSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnerProgramSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *PartnerProgram*
 */
type PartnerProgramSliceVariation = PartnerProgramSliceDefault;

/**
 * PartnerProgram Shared Slice
 *
 * - **API ID**: `partner_program`
 * - **Description**: PartnerProgram
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerProgramSlice = prismic.SharedSlice<
  "partner_program",
  PartnerProgramSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PartnerPageDocument,
      PartnerPageDocumentData,
      PartnerPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      ContactFormSlice,
      ContactFormSliceDefaultPrimary,
      ContactFormSliceVariation,
      ContactFormSliceDefault,
      EdiExpertiseSlice,
      EdiExpertiseSliceDefaultPrimaryCardsItem,
      EdiExpertiseSliceDefaultPrimary,
      EdiExpertiseSliceVariation,
      EdiExpertiseSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimaryLinksItem,
      FooterSliceDefaultPrimarySocialLinksItem,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      PartnerProgramSlice,
      PartnerProgramSliceDefaultPrimaryCardsItem,
      PartnerProgramSliceDefaultPrimary,
      PartnerProgramSliceVariation,
      PartnerProgramSliceDefault,
    };
  }
}
